services:
  - type: web
    name: crowd-ease-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: TFNSW_API_KEY
        value: your_api_key_here
